### ISSUE TITLE
new tab opens as the last tab

### ISSUE THREAD

**Issue by pucerpocok** [dmitry-kulikov/firefox-devtools-auto-open#2]
### What steps will reproduce the problem?
Have multiple tabs open, and follow a link with the "middle mouse button" (or right click link and open link in new tab).

### What is the expected result?
The new tab will be opened next to the original tab (with the devtools opened).
Also after closing the tab opened this way, firefox should jump back to the originating tab (assuming no other tabs have been visited in the meantime).

### What do you get instead?
The new tab will be opened as the last tab (with the devtools opened).
After closing the opened tab firefox will jump to the last tab.

### Additional info
I think this is not a serious issue, but it is very uncomfortable when a developer is using a lot of tabs.

| Q                | A 
|------------------|---
| Add-on version   | 1.0.3
| Firefox version  | 48.0.2
| Operating system | windows 7

**Comment by dmitry-kulikov** [comment]
Thanks for the report. Issue fixed.
Bug appears only if Developer Tools are opened on tab `open` event. To avoid this bug since version 2.0.0 Developer Tools will be opened on tab `ready` event. User can return old behavior using add-on preferences.

**Comment by pucerpocok** [comment]
Works like a charm :)
thank you for the fast feedback!
